### ISSUE TITLE
fatal error: 'Linalg/AVX.h' file not found

### ISSUE THREAD

**Issue by dselivanov** [jaredhuling/oem#1]
Hi. Package looks awesome, want to try it.  During installation got following error:

> In file included from oem_dense.cpp:3:
./DataStd.h:10:10: fatal error: 'Linalg/AVX.h' file not found
#include "Linalg/AVX.h"
         ^
1 error generated.
make: *** [oem_dense.o] Error 1
ERROR: compilation failed for package ‘oem’
removing ‘/Users/dymitriyselivanov/Library/R/3.3/library/oem’
Error: Command failed (1)

**Comment by jaredhuling** [comment]
Hi Dmitriy, what operating system are you using? What version of R? And finally does the package install on your machine from CRAN, ie `install.packages("oem")`?

**Comment by dselivanov** [comment]
Sorry. I'm on OS X. 
```r
sessionInfo()
```
> R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.1 (Sierra)
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] tools_3.3.1

Tried to install latest github version (however CRAN `install.packages("oem", type = "source")` produces the same ):
```r
devtools::install_github("jaredhuling/oem")
```
> Downloading GitHub repo jaredhuling/oem@master
from URL https://api.github.com/repos/jaredhuling/oem/zipball/master
Installing oem
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
 '/private/var/folders/82/52xsqd6d3m9031wwnr5z4yyh0000gp/T/RtmpSIdDsU/devtoolsa9e75a075a4/jaredhuling-oem-567b18c'  \
  --library='/Users/dymitriyselivanov/Library/R/3.3/library' --install-tests 
 installing *source* package ‘oem’ ...
** libs
clang++-3.8 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DUSEAVX -DUSEOMP -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dymitriyselivanov/Library/R/3.3/library/Rcpp/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppEigen/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/BH/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/bigmemory/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppArmadillo/include" -DARMA_64BIT_WORD  -mavx -fopenmp=libomp -fPIC  -Wall -mtune=core2 -g -O2  -mtune=native -Ofast  -c Rutils.cpp -o Rutils.o
clang++-3.8 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DUSEAVX -DUSEOMP -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dymitriyselivanov/Library/R/3.3/library/Rcpp/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppEigen/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/BH/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/bigmemory/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppArmadillo/include" -DARMA_64BIT_WORD  -mavx -fopenmp=libomp -fPIC  -Wall -mtune=core2 -g -O2  -mtune=native -Ofast  -c lanczos.cpp -o lanczos.o
clang++-3.8 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DUSEAVX -DUSEOMP -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dymitriyselivanov/Library/R/3.3/library/Rcpp/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppEigen/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/BH/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/bigmemory/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppArmadillo/include" -DARMA_64BIT_WORD  -mavx -fopenmp=libomp -fPIC  -Wall -mtune=core2 -g -O2  -mtune=native -Ofast  -c oem.cpp -o oem.o
clang++-3.8 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DUSEAVX -DUSEOMP -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dymitriyselivanov/Library/R/3.3/library/Rcpp/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppEigen/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/BH/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/bigmemory/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppArmadillo/include" -DARMA_64BIT_WORD  -mavx -fopenmp=libomp -fPIC  -Wall -mtune=core2 -g -O2  -mtune=native -Ofast  -c oem_big.cpp -o oem_big.o
oem_big.cpp:53:15: warning: unused variable 'n' [-Wunused-variable]
    const int n = bMPtr->nrow();
              ^
1 warning generated.
clang++-3.8 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DUSEAVX -DUSEOMP -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dymitriyselivanov/Library/R/3.3/library/Rcpp/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppEigen/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/BH/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/bigmemory/include" -I"/Users/dymitriyselivanov/Library/R/3.3/library/RcppArmadillo/include" -DARMA_64BIT_WORD  -mavx -fopenmp=libomp -fPIC  -Wall -mtune=core2 -g -O2  -mtune=native -Ofast  -c oem_dense.cpp -o oem_dense.o
In file included from oem_dense.cpp:3:
./DataStd.h:10:10: fatal error: 'Linalg/AVX.h' file not found
#include "Linalg/AVX.h"
         ^
1 error generated.
make: *** [oem_dense.o] Error 1
ERROR: compilation failed for package ‘oem’
 removing ‘/Users/dymitriyselivanov/Library/R/3.3/library/oem’
Error: Command failed (1)

**Comment by jaredhuling** [comment]
I made some changes that hopefully fix your error. Let me know if installation works now

**Comment by dselivanov** [comment]
Thanks for quick fix. Works now.
