### ISSUE TITLE
Installation error on windows

### ISSUE THREAD

**Issue by bryorsnef** [jaredhuling/oem#20]
I'm getting the following error when installing oem on windows, using devtools::install_github("jaredhuling/oem")

*** arch - i386
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c lanczos.cpp -o lanczos.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem.cpp -o oem.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem_big.cpp -o oem_big.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem_dense.cpp -o oem_dense.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem_fb_big.cpp -o oem_fb_big.o
g++ -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c oem_init.c -o oem_init.o
cc1plus.exe: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem_logistic_dense.cpp -o oem_logistic_dense.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem_logistic_sparse.cpp -o oem_logistic_sparse.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem_sparse.cpp -o oem_sparse.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem_xtx.cpp -o oem_xtx.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c oem_xval_dense.cpp -o oem_xval_dense.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG -I. -DNDEBUG -I"C:/Users/Bryor/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/BH/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/Bryor/Documents/R/win-library/3.6/RcppArmadillo/include"     -fopenmp   -O3 -c utils.cpp -o utils.o
C:\Rtools\mingw_32\bin\nm.exe: oem_init.o: File format not recognized
C:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o oem.dll tmp.def lanczos.o oem.o oem_big.o oem_dense.o oem_fb_big.o oem_init.o oem_logistic_dense.o oem_logistic_sparse.o oem_sparse.o oem_xtx.o oem_xval_dense.o utils.o -fopenmp -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lRlapack -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lR
oem_init.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'oem'
* removing 'C:/Users/Bryor/Documents/R/win-library/3.6/oem'
Error: Failed to install 'oem' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Bryor/AppData/Local/Temp/Rtmp4auAQT/file53b832487104/oem_2.0.10.tar.gz’ had non-zero exit status

**Comment by jaredhuling** [comment]
What version of R are you using? The current version of oem does not yet work with the latest versions of R.

**Comment by Kai321335** [comment]
Which version is suitable?

**Comment by Kai321335** [comment]
I met the same problem, and  the version of R is 3.6.1.

**Comment by rkb965** [comment]
> What version of R are you using? The current version of oem does not yet work with the latest versions of R.

What is the latest version of R that is compatible with oem? Thank you!

**Comment by Kai321335** [comment]
The version of R is 3.6.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rkb965"<notifications@github.com&gt;; 
发送时间: 2020年5月1日(星期五) 下午2:05
收件人: "jaredhuling/oem"<oem@noreply.github.com&gt;; 
抄送: "赖恺瀛"<459757390@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jaredhuling/oem] Installation error on windows (#20)





  
What version of R are you using? The current version of oem does not yet work with the latest versions of R.
  
What is the latest version of R that is compatible with oem? Thank you!

**Comment by rkb965** [comment]
> The version of R is 3.6.1

Sorry, my question was meant for @jaredhuling

**Comment by jaredhuling** [comment]
The most recent version of oem works with R 4.0.0
