### ISSUE TITLE
Mnet or Snet penalties

### ISSUE THREAD

**Issue by khotilov** [jaredhuling/oem#3]
Were there any plans to add Mnet or Snet penalties? I might give it a try, if you don't mind.

**Comment by jaredhuling** [comment]
Could you send some references on those penalties?

**Comment by khotilov** [comment]
Here are a couple of references
Mnet = MCP + Ridge: http://myweb.uiowa.edu/pbreheny/publications/mnet.pdf
Snet = SCAD + Ridge: http://www.stat.purdue.edu/~junxie/papers2/scad_l2_reprint.pdf
Some available implementations: https://cran.r-project.org/package=ncvreg and https://cran.r-project.org/package=mpath

**Comment by jaredhuling** [comment]
Thanks!

**Comment by jaredhuling** [comment]
I have plans for a few more penalties, so let me know if you have any other requests

**Comment by khotilov** [comment]
Awesome! Thank you!

Just a couple of comments:
- Since now you've got a "complete set", why not to limit the interface to something like `penalty = c("enet",  "ols", "mnet", "snet", "grp.enet")` and let a user to steer with alpha?
- cv functions also need to be updated.

**Comment by jaredhuling** [comment]
@khotilov regarding cv functions: xval.oem was already fixed, but with the latest update i've fixed cv.oem.

regarding the first point: allowing the separate penalties "mcp" vs "mcp.net" allows a bit more flexibility for now until I allow the user to specify *multiple* values of alpha at a time. Allowing multiple values of alpha at a time will require some significant code changes and re-organization so I don't expect it to happen very soon. However, once I do that it should allow me to simplify the penalty options significantly without any loss of flexibility
